#+OPTIONS: H:3 num:2

* Emacs相关中文问题以及解决方案

本文力图收集整理 Emacs 使用过程中的中文相关问题以及解决方案. 有问题欢迎反馈, 也欢迎 issue 或者其他方式补充问题, 修正或者增加解决方案.

changelog:

- 2015-12-27 文件编码问题整理
- 2015-12-25 中文断行(org 导出 html 有空格)等问题
- 2015-06-15 构思好基本结构, 通过 QQ 群/微信群 收集整理, 逐步完善中.

** 目录        :TOC_3_gh:
 - [[#emacs相关中文问题以及解决方案][Emacs相关中文问题以及解决方案]]
   - [[#emacs-中文基础][Emacs 中文基础]]
     - [[#emacs-的各种字符集][Emacs 的各种字符集]]
     - [[#中文断行][中文断行]]
     - [[#中文字体设置][中文字体设置]]
     - [[#日历设置][日历设置]]
   - [[#中文输入][中文输入]]
     - [[#外部中文输入法][外部中文输入法]]
     - [[#内置的输入法][内置的输入法]]
     - [[#输入法相关-mode][输入法相关 mode]]
   - [[#org-的中文问题][org 的中文问题]]
     - [[#table-中英文对齐等][table 中英文对齐等]]
     - [[#org-导出中文-html-的空格问题][org 导出中文 html 的空格问题]]
     - [[#org-以及-latex-等导出中文-pdf][org 以及 LaTex 等导出中文 pdf]]
   - [[#其他中文相关工具][其他中文相关工具]]
     - [[#magit-的中文问题][magit 的中文问题]]
     - [[#pinyin-search][pinyin-search]]
     - [[#ace-pinyin][ace-pinyin]]
     - [[#find-by-pinyin-dired][find-by-pinyin-dired]]
     - [[#emacs-hz2py][emacs-hz2py]]
     - [[#pyim-hanzi2pinyin][pyim-hanzi2pinyin]]
     - [[#ido-pinyin][ido-pinyin]]
     - [[#pangu-spacing][pangu-spacing]]
     - [[#chinese-word-at-point][chinese-word-at-point]]
     - [[#chinese-fonts-setup][chinese-fonts-setup]]
     - [[#chinese-pyim-bigdict][chinese-pyim-bigdict]]
     - [[#chinese-in-spacemacs][Chinese in Spacemacs]]
     - [[#emacs-cedict][Emacs cedict]]
     - [[#欢迎补充][欢迎补充]]
   - [[#参考和鸣谢][参考和鸣谢]]

** Emacs 中文基础

*** Emacs 的各种字符集

Emacs 中的文件编码问题跟其他编辑器不大一样,  ~M-x describe-coding-system~ 能看到所有可选择编码, 除了常见的 utf-8 这样的, dos/unix 这样的换行符也作为了编码的一部分. 作为比较通用的方式, 一般建议没有特殊需要都使用 utf-8 编码,  unix 还是 dos 看个人需要.

默认配置下, mode line 最左会显示当前文件编码以及换行符格式, 比如 U(Unix) 标示 UTF-8 编码, UNIX 格式换行符,鼠标点击可以查看更多详情.

Unicad http://www.emacswiki.org/emacs/Unicad 是一个自动检测文件编码的 mode ,  有看到反馈说有时候不能成功检测: Unicad is short for Universal Charset Auto Detector. It is an Emacs-Lisp port of Mozilla Universal Charset Detector.


#+BEGIN_SRC Emacs lisp
  (set-language-environment "UTF-8")
  (set-default-coding-systems 'utf-8)
  (set-buffer-file-coding-system 'utf-8-unix)
  (set-clipboard-coding-system 'utf-8-unix)
  (set-file-name-coding-system 'utf-8-unix)
  (set-keyboard-coding-system 'utf-8-unix)
  (set-next-selection-coding-system 'utf-8-unix)
  (set-selection-coding-system 'utf-8-unix)
  (set-terminal-coding-system 'utf-8-unix)
  (setq locale-coding-system 'utf-8)
  (prefer-coding-system 'utf-8)

  # 特别注意下文是针对 windows 平台单独处理, windows 某些场景需要 gbk 才能正常
  (when (eq system-type 'windows-nt)
    (setq locale-coding-system 'gbk-dos)
    (set-selection-coding-system 'gbk-dos)
    (set-next-selection-coding-system 'gbk-dos)
    (set-clipboard-coding-system 'gbk-dos)))
#+END_SRC

如果一个非 utf-8 编码, 比如 gbk 编码的文件打开, 可能 Emacs 会乱码, 这时候 ~M-x revert-buffer-with-coding-system~ 选择 gbk 即可.

*** 中文断行

如果开启了 auto-fill 或者使用 refill-mode 等,  Emacs 会根据 fill-column 的大小，在合适的位置插入换行符. 这时候再导出成 html 等格式, 可能导致被自动断行的中文之间多一个空格(中文和英文以及英文与英文之间的空格还是自然的), 一种建议是关掉或者不是用自动断行, 采用 truncate-lines 的方式让 Emacs 自动根据 frame 大小处理成显示层的断行.

另外一种比较常见的做法是在导出的时候, 通过导出的过滤器机制, 导出之前去掉中文之间的换行的模式, 具体参考有 zwz (http://zwz.github.io/) 和 [[http://emacs-china.org/blog/2015/04/20/org-mode-%E5%AF%BC%E5%87%BA-html-%E6%97%B6%E5%88%A0%E9%99%A4%E4%B8%AD%E6%96%87%E4%B8%8E%E4%B8%AD%E6%96%87%E4%B9%8B%E9%97%B4%E5%A4%9A%E4%BD%99%E7%9A%84%E7%A9%BA%E6%A0%BC/][tumashu]] 两种类似的实现:


#+BEGIN_SRC
;;; 下面一段是 Feng Shu 的
(defun eh-org-clean-space (text backend info)
  "在export为HTML时，删除中文之间不必要的空格"
  (when (org-export-derived-backend-p backend 'html)
    (let ((regexp "[[:multibyte:]]")
          (string text))
      ;; org默认将一个换行符转换为空格，但中文不需要这个空格，删除。
      (setq string
            (replace-regexp-in-string
             (format "\\(%s\\) *\n *\\(%s\\)" regexp regexp)
             "\\1\\2" string))
      ;; 删除粗体之前的空格
      (setq string
            (replace-regexp-in-string
             (format "\\(%s\\) +\\(<\\)" regexp)
             "\\1\\2" string))
      ;; 删除粗体之后的空格
      (setq string
            (replace-regexp-in-string
             (format "\\(>\\) +\\(%s\\)" regexp)
             "\\1\\2" string))
      string)))
(add-to-list 'org-export-filter-paragraph-functions
             'eh-org-clean-space)


;;; 下面一段是 zwz 的, 作者声明只适应 org-mode 8.0 以及以上版本
(defun clear-single-linebreak-in-cjk-string (string)
  "clear single line-break between cjk characters that is usually soft line-breaks"
  (let* ((regexp "\\([\u4E00-\u9FA5]\\)\n\\([\u4E00-\u9FA5]\\)")
         (start (string-match regexp string)))
    (while start
      (setq string (replace-match "\\1\\2" nil nil string)
            start (string-match regexp string start))))
  string)

(defun ox-html-clear-single-linebreak-for-cjk (string backend info)
  (when (org-export-derived-backend-p backend 'html)
    (clear-single-linebreak-in-cjk-string string)))

(add-to-list 'org-export-filter-final-output-functions
             'ox-html-clear-single-linebreak-for-cjk)
#+END_SRC




*** 中文字体设置

为了保证显示效果, 一般使用中英文等宽字体(一个中文字显示宽度等于俩个英文字母显示宽度), 推荐字体:

- Ubuntu Mono
- YaHei Consolas hybrid
- 文泉驿等宽微米黑

*** 日历设置

Emacs 中有日历，而且可以称之为一个系统，因为其中除了最常用的日历之外，还有其他的近十种历法，其中有日记、约会提醒、纪念日提示以及节假日提示等等。其中的历法包括中国的农历、希伯来历、伊斯兰历、法国革命历、中美玛雅历等等，可以根据经纬度告知你的所在的每天日出日落的时间等等。

Emacs 自带 calc-china.el

一下为设置中文里的 ‘celestial-stem’ (天干) 和 ‘terrestrial-branch’ (地支):

#+BEGIN_SRC Emacs lisp
(setq chinese-calendar-celestial-stem
          ["甲" "乙" "丙" "丁" "戊" "己" "庚" "辛" "壬" "癸"]
          chinese-calendar-terrestrial-branch
          ["子" "丑" "寅" "卯" "辰" "巳" "午" "未" "申" "酉" "戌" "亥"])
#+END_SRC

设置阳历节日和阴历节日(参考 fog_proxy @ http://www.linuxsir.org/bbs/thread232256.html):

#+BEGIN_SRC Emacs lisp
;;; 补充用法: holiday-float m w n 浮动阳历节日， m 月的第 n 个星期 w%7
(setq general-holidays '((holiday-fixed 1 1   "元旦")
                         (holiday-fixed 2 14  "情人节")
                         (holiday-fixed 4 1   "愚人节")
                         (holiday-fixed 12 25 "圣诞节")
                         (holiday-fixed 10 1  "国庆节")
                         (holiday-float 5 0 2 "母亲节")   ;5月的第二个星期天
                         (holiday-float 6 0 3 "父亲节")
                         ))
(setq local-holidays '((holiday-chinese 1 15  "元宵节 (正月十五)")
                       (holiday-chinese 5 5   "端午节 (五月初五)")
                       (holiday-chinese 9 9   "重阳节 (九月初九)")
                       (holiday-chinese 8 15  "中秋节 (八月十五)")
                       ;; 生日
                       (birthday-fixed 9 28  "爸爸生日(1950)")
                       (birthday-fixed 10 1  "妈妈生日(1953)")
                       (holiday-chinese 5 29 "老婆生日")           ;阴历生日

                       (holiday-lunar 1 1 "春节" 0)
                       ))

#+END_SRC

另外一种中文阴历节日的 holiday-lunar 的写法参考自:  http://xlambda.com/blog/2010/01/11/customize-calendar-in-emacs/


更强大的中文日历工具:

- chinese-calendar.el calendar for chinese
  http://www.newsmth.net/bbsanc.php?path=%2Fgroups%2Fcomp.faq%2FEmacs%2Farchives%2Farchive2005%2FM.1121269541.D0

-  William Xu 写的 中文版日历 https://github.com/xwl/cal-china-x/blob/master/cal-china-x.el

** 中文输入

*** 外部中文输入法

个人用搜狗中文输入法的还可以

*** 内置的输入法

默认情况下 toggle-input-method 命令切换输入法.

*** 输入法相关 mode

- https://github.com/danking/eim-py
  eim-py: An Emacs Input Method extension for smart pinyin

- https://github.com/gongzhitaao/chinese-wubi
  Emacs 中使用五笔输入法: Chinese Wubi (五笔) input method for Emacs based on quail package.


- chinese-pyim  https://github.com/tumashu/chinese-pyim
  chinese-pyim是从eim拼音输入法进化来的，个人感觉比eim拼音输入法好用

- https://github.com/cute-jumper/fcitx.el
  Make fcitx better in Emacs.

- https://github.com/tumashu/chinese-remote-input
  chinese-remote-input
  在emacs中，通过智能手机输入法（比如：android语音输入法）远程输入中文。

- scel2pyim https://github.com/E-Neo/scel2pyim
  一个个将搜狗输入法 scel 细胞词库转换为 chinese-pyim 文本词库的小工具。


- https://github.com/district10/gat
  Gat, Chinese Input Method, works in Emacs

** org 的中文问题

*** table 中英文对齐等

因为 Emacs 处理字体的方式的问题, 即使设置字体为等宽字体(一个中文相当于两个英文宽度), org 中的 table 出现中文经常都无法工整的对齐.
需要分别对中英文字体设置合适的大小. 处理该问题有现成的方案: https://github.com/tumashu/chinese-fonts-setup . 其中默认定义了各个
系统平台常见的字体以及中英文字体搭配, 使得 org table 里的出现中文也能很好的对齐. 如果安装好以后显示的字体过大, 可以通过
cfs-increase-fontsize/cfs-decrease-fontsize 调整选择合适的大小.

更多参考资料:

- 狠狠地折腾了一把Emacs中文字体 BY  BAO HAOJUN http://baohaojun.github.io/perfect-emacs-chinese-font.html
- 折腾 Emacs BY zhuoqiang http://zhuoqiang.me/torture-emacs.html


*** org 导出中文 html 的空格问题

严格来说跟 org 没什么关系, 参见上文的 [[#中文断行][中文断行]]

*** org 以及 LaTex 等导出中文 pdf

导出中文也分直接转 LaTex 再转 pdf 以及先转 html 再转 pdf 等各种方式, 中间方案的可以参考这个 http://blog.hickwu.com/posts/339

arthur@微信群 http://home.ustc.edu.cn/~zpj/doc/TeX/xetex-tutorial.pdf

** 其他中文相关工具


*** magit 的中文问题

按照前面的设置好编码一般不会有问题了. 有收到一种情况是 linux 下的终端的问题, 有网友这样尝试解决了:

#+BEGIN_SRC shell
vi /etc/profile
# 添加
export LESSCHARSET=utf-8
# 填完以后执行
source /etc/profile
#+END_SRC

*** pinyin-search

https://github.com/xuchunyang/pinyin-search.el

Search Chinese by the first letter of Chinese pinyin.

*** ace-pinyin

https://github.com/cute-jumper/ace-pinyin

Jump to Chinese characters using ace-jump-char-mode or avy-goto-char :
input the first letter of the pinyin of the Chinese character, then use
ace-jump-char-mode or avy-goto-char to jump to it.

*** find-by-pinyin-dired

https://github.com/redguardtoo/find-by-pinyin-dired

Find file by first Pinyin characters of Chinese Hanzi. 输入拼音首字母定位对应的中文目录/文件

*** emacs-hz2py

https://github.com/kawabata/emacs-hz2py

Hanzi to Pinyin converter for Emacs


*** pyim-hanzi2pinyin

是一个汉字转拼音得函数，包含在chinese-pyim中，主要用于生成词库 @tushuma 天然二呆

*** ido-pinyin

https://github.com/pengpengxp/ido-pinyin

Make ido support chinese pinyin 2015-06-14: 新生不久, 可能问题还比较多 :)

*** pangu-spacing

emacs minor-mode to add space between Chinese and English characters.

https://github.com/coldnew/pangu-spacing

看演示 gif 挺好玩.

*** chinese-word-at-point

Get (most likely) Chinese word under the cursor in Emacs

中文分词跟英文可以时候完全不是一回事, 徐春阳同学弄的这个, 依赖外部分词的命令行: 可以用结巴分词或者 SCWS (简易中文分词系统).

https://github.com/xuchunyang/chinese-word-at-point.el



*** chinese-fonts-setup

https://github.com/tumashu/chinese-fonts-setup

emacs中文字体配置工具。可以快速方便的的实现中文字体和英文字体等宽（也就是常说的中英文对齐）

*** chinese-pyim-bigdict

https://github.com/tumashu/chinese-pyim-bigdict

这个文件是一个 Chinese-pyim 拼音词库文件，词量超过100万，词库大于20M，这个词库仅供个人使用。

*** Chinese in Spacemacs

- [2015-06-16 15:21:58] 最新消息, 子龙山人给 Spacemacs 贡献了一个中文 layer , 已经提交 pull request:
  https://github.com/syl20bnr/spacemacs/pull/2024 , 这是使用说明：
  https://github.com/andyque/spacemacs/blob/add-chinese-layer/contrib/chinese/README.org


https://github.com/et2010/Chinese

Spacemacs configuration layer for easy writing in Chinese


*** Emacs cedict

https://github.com/danmey/cedict.el

Emacs interface to Chinese-English dictionary in CEDICT format.


*** 欢迎补充


** 参考和鸣谢

本文档由 hick 初始整理, 主要是在 Emacs 微信群中 @求其 @arthur @子龙山人 @peng 等讨论中文 org 中 table 中英文混排对齐的时候,
发现有各种做法, 引发整理中文问题的想法.

欢迎提议和补充条目.
