#+OPTIONS: H:3 num:2

* Emacs相关中文问题以及解决方案

本文力图收集整理 Emacs 使用过程中的中文相关问题以及解决方案. 欢迎 issue 或者其他方式补充问题, 修正或者增加解决方案.

changelog:

- 2015-06-15 构思好基本结构, 通过 QQ 群/微信群 收集整理, 逐步完善中.

** 目录        :TOC_3_gh:
 - [[#emacs相关中文问题以及解决方案][Emacs相关中文问题以及解决方案]]
     - [[#emacs-中使用中文的基础][Emacs 中使用中文的基础]]
         - [[#emacs-的各种字符集问题][Emacs 的各种字符集问题]]
         - [[#文件编码][文件编码]]
         - [[#中文字体设置][中文字体设置]]
         - [[#日历设置][日历设置]]
     - [[#中文输入][中文输入]]
         - [[#外部中文输入法][外部中文输入法]]
         - [[#内置的输入法][内置的输入法]]
         - [[#输入法相关-mode][输入法相关 mode]]
     - [[#org-的中文问题][org 的中文问题]]
         - [[#table-中英文对齐等][table 中英文对齐等]]
         - [[#导出中文-pdf][导出中文 pdf]]
     - [[#其他中文相关工具][其他中文相关工具]]
         - [[#pinyin-search][pinyin-search]]
         - [[#ace-pinyin][ace-pinyin]]
         - [[#find-by-pinyin-dired][find-by-pinyin-dired]]
         - [[#emacs-hz2py][emacs-hz2py]]
         - [[#pyim-hanzi2pinyin][pyim-hanzi2pinyin]]
         - [[#ido-pinyin][ido-pinyin]]
         - [[#pangu-spacing][pangu-spacing]]
         - [[#chinese-word-at-point][chinese-word-at-point]]
         - [[#chinese-fonts-setup][chinese-fonts-setup]]
         - [[#chinese-pyim-bigdict][chinese-pyim-bigdict]]
         - [[#chinese-in-spacemacs][Chinese in Spacemacs]]
         - [[#emacs-cedict][Emacs cedict]]
         - [[#欢迎补充][欢迎补充]]
     - [[#参考和鸣谢][参考和鸣谢]]

** Emacs 中使用中文的基础

*** Emacs 的各种字符集问题

各种字符集以及不同平台的格式相关问题.

*** 文件编码

自动检测和修改编码等.

默认配置下, mode line 最左会显示当前文件编码以及换行符格式, 比如 U(Unix) 标示 UTF-8 编码, UNIX 格式换行符,
鼠标点击可以查看更多详情.

- revert-buffer-with-coding-system

  重新选择编码方式载入当前文件, 不会转换原文件编码.

- set-buffer-file-coding-system

  转换当前 buffer(打开文件) 的编码.

另外还有不太常用的 `describe-current-coding-system` 可以查看 Emacs 的编码设置情况.

*** 中文字体设置

包括推荐的字体等.

*** 日历设置

Emacs 中有日历，而且可以称之为一个系统，因为其中除了最常用的日历之外，
还有其他的近十种历法，其中有日记、约会提醒、纪念日提示以及节假日提示等
等。其中的历法包括中国的农历、希伯来历、伊斯兰历、法国革命历、中美玛雅
历等等，可以根据经纬度告知你的所在的每天日出日落的时间等等。

Emacs 自带 calc-china.el #HICKTODO 可以去看看.


Here is how to display the ‘celestial-stem’ (天干) and the ‘terrestrial-branch’ (地支) in Chinese:

#+BEGIN_SRC Emacs lisp
(setq chinese-calendar-celestial-stem
          ["甲" "乙" "丙" "丁" "戊" "己" "庚" "辛" "壬" "癸"]
          chinese-calendar-terrestrial-branch
          ["子" "丑" "寅" "卯" "辰" "巳" "午" "未" "申" "酉" "戌" "亥"])
#+END_SRC

设置阳历节日和阴历节日(参考 fog_proxy @ http://www.linuxsir.org/bbs/thread232256.html):

#+BEGIN_SRC Emacs lisp
;;; 补充用法: holiday-float m w n 浮动阳历节日， m 月的第 n 个星期 w%7
(setq general-holidays '((holiday-fixed 1 1   "元旦")
                         (holiday-fixed 2 14  "情人节")
                         (holiday-fixed 4 1   "愚人节")
                         (holiday-fixed 12 25 "圣诞节")
                         (holiday-fixed 10 1  "国庆节")
                         (holiday-float 5 0 2 "母亲节")   ;5月的第二个星期天
                         (holiday-float 6 0 3 "父亲节")
                         ))
(setq local-holidays '((holiday-chinese 1 15  "元宵节 (正月十五)")
                       (holiday-chinese 5 5   "端午节 (五月初五)")
                       (holiday-chinese 9 9   "重阳节 (九月初九)")
                       (holiday-chinese 8 15  "中秋节 (八月十五)")
                       ;; 生日
                       (birthday-fixed 9 28  "爸爸生日(1950)")
                       (birthday-fixed 10 1  "妈妈生日(1953)")
                       (holiday-chinese 5 29 "老婆生日")           ;阴历生日

                       (holiday-lunar 1 1 "春节" 0)
                       ))

#+END_SRC

另外一种中文阴历节日的 holiday-lunar 的写法参考自:  http://xlambda.com/blog/2010/01/11/customize-calendar-in-emacs/


更强大的中文日历工具:

- chinese-calendar.el calendar for chinese
  http://www.newsmth.net/bbsanc.php?path=%2Fgroups%2Fcomp.faq%2FEmacs%2Farchives%2Farchive2005%2FM.1121269541.D0

-  William Xu 写的 中文版日历 https://github.com/xwl/cal-china-x/blob/master/cal-china-x.el

** 中文输入

*** 外部中文输入法

个人用搜狗中文输入法的还可以

*** 内置的输入法

默认情况下 toggle-input-method 命令切换输入法.

*** 输入法相关 mode

- https://github.com/danking/eim-py
  eim-py: An Emacs Input Method extension for smart pinyin

- https://github.com/gongzhitaao/chinese-wubi
  Emacs 中使用五笔输入法: Chinese Wubi (五笔) input method for Emacs based on quail package.


- chinese-pyim  https://github.com/tumashu/chinese-pyim
  chinese-pyim是从eim拼音输入法进化来的，个人感觉比eim拼音输入法好用

- https://github.com/cute-jumper/fcitx.el
  Make fcitx better in Emacs.

- https://github.com/tumashu/chinese-remote-input
  chinese-remote-input
  在emacs中，通过智能手机输入法（比如：android语音输入法）远程输入中文。

- scel2pyim https://github.com/E-Neo/scel2pyim
  一个个将搜狗输入法 scel 细胞词库转换为 chinese-pyim 文本词库的小工具。


- https://github.com/district10/gat
  Gat, Chinese Input Method, works in Emacs

** org 的中文问题

*** table 中英文对齐等

这个就有好几个方案

*** org 以及 LaTex 等到处中文 pdf

导出中文也分直接转 LaTex 再转 pdf 以及先转 html 再转 pdf 等各种方式.

arthur@微信群 http://home.ustc.edu.cn/~zpj/doc/TeX/xetex-tutorial.pdf


** 其他中文相关工具

这里的篇幅足够长的时候, 提升为一级条目.

*** magit 的中文问题



*** pinyin-search

https://github.com/xuchunyang/pinyin-search.el

Search Chinese by the first letter of Chinese pinyin.

*** ace-pinyin

https://github.com/cute-jumper/ace-pinyin

Jump to Chinese characters using ace-jump-char-mode or avy-goto-char :
input the first letter of the pinyin of the Chinese character, then use
ace-jump-char-mode or avy-goto-char to jump to it.

*** find-by-pinyin-dired

https://github.com/redguardtoo/find-by-pinyin-dired

Find file by first Pinyin characters of Chinese Hanzi. 输入拼音首字母定位对应的中文目录/文件

*** emacs-hz2py

https://github.com/kawabata/emacs-hz2py

Hanzi to Pinyin converter for Emacs


*** pyim-hanzi2pinyin

是一个汉字转拼音得函数，包含在chinese-pyim中，主要用于生成词库 @tushuma 天然二呆

*** ido-pinyin

https://github.com/pengpengxp/ido-pinyin

Make ido support chinese pinyin 2015-06-14: 新生不久, 可能问题还比较多 :)

*** pangu-spacing

emacs minor-mode to add space between Chinese and English characters.

https://github.com/coldnew/pangu-spacing

看演示 gif 挺好玩.

*** chinese-word-at-point

Get (most likely) Chinese word under the cursor in Emacs

中文分词跟英文可以时候完全不是一回事, 徐春阳同学弄的这个, 依赖外部分词的命令行: 可以用结巴分词或者 SCWS (简易中文分词系统).

https://github.com/xuchunyang/chinese-word-at-point.el



*** chinese-fonts-setup

https://github.com/tumashu/chinese-fonts-setup

emacs中文字体配置工具。可以快速方便的的实现中文字体和英文字体等宽（也就是常说的中英文对齐）

*** chinese-pyim-bigdict

https://github.com/tumashu/chinese-pyim-bigdict

这个文件是一个 Chinese-pyim 拼音词库文件，词量超过100万，词库大于20M，这个词库仅供个人使用。

*** Chinese in Spacemacs

- [2015-06-16 15:21:58] 最新消息, 子龙山人给 Spacemacs 贡献了一个中文 layer , 已经提交 pull request:
  https://github.com/syl20bnr/spacemacs/pull/2024 , 这是使用说明：
  https://github.com/andyque/spacemacs/blob/add-chinese-layer/contrib/chinese/README.org


https://github.com/et2010/Chinese

Spacemacs configuration layer for easy writing in Chinese


*** Emacs cedict

https://github.com/danmey/cedict.el

Emacs interface to Chinese-English dictionary in CEDICT format.


*** 欢迎补充


** 参考和鸣谢

本文档由 hick 初始整理, 主要是在 Emacs 微信群中 @求其 @arthur @子龙山人 @peng 等讨论中文 org 中 table 中英文混排对齐的时候,
发现有各种做法, 引发整理中文问题的想法.

欢迎提议和补充条目.
